<?php $isLogin = $this->helper('customer')->isLoggedIn()?>

<?php if(!$isLogin){?>
<?php }?>

<?php
	$data=$this->getData();
	$provider = $data['provider'];
	$account = isset($data['account']) ? $data['account'] : null;
	//var_dump($account);die();
	$title = $this->__($this->getTitle($provider));
	$text = $this->__($this->getText($provider));
	$width = $this->getWidth($provider);
	$height = $this->getHeight($provider);
	$url = $this->getBTUrl($provider,$account);
?>
<button class="bt-login-social sso_login bt-login <?=$provider?>" data-url="<?=$url?>" data-width="<?=$width?>" data-height="<?=$height?>" href="#" alt="<?=$title?>" title="<?=$title?>" >
	<span><span><?=$text?></span></span>
</button>
