<?php
	$data=$this->getData();
	$provider = $data['provider'];
	$account = isset($data['account']) ? $data['account'] : null;
	$skipUrl = isset($data['skipUrl']) ? $data['skipUrl'] : false;
	
	
	//var_dump($account);die();
	$title = $this->__($this->getTitle($provider));
	$text = $this->__($this->getText($provider));

	$width = 'data-width="'.$this->getWidth($provider).'"';
	$height ='data-height="'.$this->getHeight($provider).'"';
	$url = ($skipUrl!=true)?'data-url="'.$this->getBTUrl($provider,$account).'"':"";
	
	if($url==""){
		$text = str_replace('Sign in','',$text);
	}
?>
<button class="bt-login-social sso_login bt-login <?=$provider?> <?=($url==""?"unlinked":$url)?>" <?=$url?> <?=$width?> <?=$height?> href="#" alt="<?=$title?>" title="<?=$title?>" >
	<span><span><?=$text?></span></span>
</button>
