<?php //die('in block');?>
<?php 
	$unusedButton = $this->getSsoBtns();
	$temp = $unusedButton;
	$numberShow = $this->getNumberShow();
	$countAll = 0;
	$countMain = 0;
	$count = 0;

	$data=$this->getData();
	$isOther = isset($data['isOther'])?$data['isOther']:false;

?>

<div id="sociallogin_button"  class="<?php echo ($this->getDirection() == 'left') ? "left" : "right" ?>">	



<?php if($isOther): ?>
	<?php $usedButtons = $this->getUsedSsoBtns(); ?>
	<h3>Soical Logins attached to your account:</h3>
	<ul class="<?php echo ($this->getDirection() == 'left') ? "left" : "right" ?>">
		<?php foreach($usedButtons as $button):?>		
			<li class="button left bare"> <?=$button['button']?> </li>		
		<?php endforeach;?>  		
	</ul>

	<?php if(count($unusedButton)>0): ?>
		<h4>Would you like to sign in with other providers?</h4>
		<p>Allowing other providers to sign up through can help you access the site easier while providing the security you want with your account.</p>
	<?php endif; ?>
<?php endif; ?>


	<ul class="<?php echo ($this->getDirection() == 'left') ? "left" : "right" ?>">
	<?php foreach($unusedButton as $key => $button):?>	
		<?php $check =$button['check'];?>
		<?php if($check): unset($temp[$key]);?>					
			<li class="button left bare"> <?php echo $button['button']?> </li>	
			<?php ++$countMain ;?>			
		<?php endif;?>
		<?php if($countMain == $numberShow){break;} ?>
	<?php endforeach;?>  		
	</ul>	
	<?php if(count($temp)):?>
		<?php $noEmpty = false;?>
		<?php foreach($temp as $tem):?>
			<?php if($tem['check']):?>
				<?php $noEmpty = true;?>
			<?php endif;?>
		<?php endforeach;?>
		<?php if($noEmpty):?>
		<div class="sociallogin-other">
		
			<div id="sociallogin-other-div">		
				<a id="sociallogin-other-a"> 
				<span class="sociallogin-other-span">
					<?php echo $this->__('Other login') ?>
				</span>			
				<span class="sociallogin-other-span-img-popup"></span></a>
					<ul class="sociallogin-other-button" id="sociallogin-other-button" style="display:none">
					<?php foreach($temp as $button):?>				
						<?php $check = $button['check']; ?>
						<?php if($check): $count ++;?>				
							<li class="button left other-button"> <?php echo $button['button'] ?> </li>		
						<?php endif;?>			
					<?php endforeach;?>  
					</ul>
			
			</div>
		</div>
		<?php endif; ?>
	<?php endif; ?>
</div>

<div class="clear"></div>