<?php
/**
 * @var $this Wsu_NewtworkSecuritiesTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('#') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-ldap" target="_blank" style="float:right;">
            <img src="#" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>
        <h4><?php echo $this->helper('wsu_newtworksecurities')->__('LDAP controlls let you .'); ?></h4>
        <p style="margin-bottom:0;"><?php echo $this->helper('wsu_newtworksecurities')->__('Full overview available'); ?> <a href="<?php echo $this->escapeHtml($this->helper('wsu_newtworksecurities')->__('#')); ?>" target="_blank"><?php echo $this->helper('wsu_newtworksecurities')->__('here'); ?></a>.</p>
    </div>
    <p>It should be noted that if you try to trun this module on and you are using a local development environment then you must but with in the network access to the LDAP services.  You may need to VPN to fully if you are outside the network.</p>
</div>