<?php
/**
 * @var $this Wsu_AdminldapTheme_Block_Adminhtml_System_Config_Fieldset_Hint
 */
?>
<div class="box">
    <div style="background:url('#') no-repeat left center;padding-left:55px;min-height:42px;">
        <a href="https://github.com/washingtonstateuniversity/WSUMAGE-extstub" target="_blank" style="float:right;">
            <img src="#" alt="Fork me on GitHub" title="Fork me on GitHub" />
        </a>

    </div>
</div>
<h2>Stub life</h2>
<p>This is a module that is just a Stub.  It doesn't do anything but waste a minor amount of resources to be loaded up in the path of all the other extensions.  The goal is that you will take this stub and turn it into something useful.  Simply put, with a case sensitive sreach for `Stub`, `stub` and doing the same on the file and fold names as well, you will have forked your own extention and are ready to create your moddule.  Read more on this that and more <a href="#" target="_blank">here</a>.</p>
<!-- note we will want to place a quick image of the structure here -->