<?php $isLogin = $this->helper('customer')->isLoggedIn()?>

<?php if(!$isLogin){?>
<?php }?>

<?php


	//$providers = Mage::getSingleton('wsu_networksecurities/sso_providers');
	//$provider = $providers->getProvider('faceboook');
	//$provider = Mage::registry('provider');
	$data=$this->getData();
	$provider = $data['provider'];
	
	
	//$provider = $this->getData('provider');//$this->getProvider();// note should be $provider->getUser(); etc..
	$user = $this->getUser($provider);
	$title = $this->__($this->getTitle($provider));
	$text = $this->__($this->getText($provider));
	$width = $this->getWidth($provider);
	$height = $this->getHeight($provider);
	$url = $this->getBTUrl($provider);
	
	
	
?>
<button class="bt-login-social sso_login bt-login <?=$provider?>" data-url="<?=$url?>" data-width="<?=$width?>" data-height="<?=$height?>" href="#" alt="<?=$title?>" title="<?=$title?>" >
	<span><span><?=$text?></span></span>
</button>
