<?php
/* @var $this Wsu_networksecurities_Block_Honeypot */
$themes = $this->getHoneypotTheme();
?><div class="input-box" id="<?=$themes["ids"]?>"><label for="<?=$themes["ids"]?>">website:</label><br/><input id="domain" type="text" name="<?=$themes["name"]?>" class="input-text" type="password" style="border: 1px solid rgb(192, 31, 47); width: 253px;"/><script> document.observe('dom:loaded', function () { 
//$('<?=$themes["ids"]?>').hide();
 }); </script></div>