<?php
/* @var $this Wsu_networksecurities_Block_Honeypot */
$themes = $this->getHoneypotTheme();
$type = 'type="text"';
?><div class="input-box" id="<?=$themes["ids"]?>"><label for="<?=$themes["ids"]?>">website:</label><br/><input id="<?=$themes["ids"]?>_domain" <?=$type?>  name="<?=$themes["name"]?>" class="input-text" style="border: 1px solid rgb(192, 31, 47); width: 253px;"/><script> document.observe('dom:loaded', function () { $('<?=$themes["ids"]?>').hide(); }); </script></div>