
<?php $arrayButton = $this->makeArrayButton(); $temp = $arrayButton; ?>
<?php $numberShow = $this->getNumberShow();?>
<?php $countAll = 0;?>
<?php $countMain = 0;?>
<?php $count = 0;?>

<div id="sociallogin_button"  class="<?php echo ($this->getDirection() == 'left') ? "left" : "right" ?>">	
	<ul class="<?php echo ($this->getDirection() == 'left') ? "left" : "right" ?>">
	<?php foreach($arrayButton as $key => $button):?>	
		<?php $check =$button['check'];?>
		<?php if($check): unset($temp[$key]);?>					
			<li class="button left"> <?php echo $button['button']?> </li>
			<!--<script type="text/javascript">
				$('<?php echo $button['id'] ?>').addClassName('visible');
				$('<?php echo $button['id'] ?>' ).setStyle('min-width: 80px');
			</script>-->	
			<?php ++$countMain ;?>			
		<?php endif;?>
		<?php if($countMain == $numberShow){break;} ?>
	<?php endforeach;?>  		
	</ul>	
	<?php if(count($temp)):?>
		<?php $noEmpty = false;?>
		<?php foreach($temp as $tem):?>
			<?php if($tem['check']):?>
				<?php $noEmpty = true;?>
			<?php endif;?>
		<?php endforeach;?>
		<?php if($noEmpty):?>
		<div class="sociallogin-other">
		
			<div id="sociallogin-other-div">		
				<a id="sociallogin-other-a"> 
				<span class="sociallogin-other-span">
					<?php echo $this->__('Other login') ?>
				</span>			
				<span class="sociallogin-other-span-img-popup"></span></a>
					<ul class="sociallogin-other-button" id="sociallogin-other-button" style="display:none">
					<?php foreach($temp as $button):?>				
						<?php $check = $button['check']; ?>
						<?php if($check): $count ++;?>				
							<li class="button left other-button"> <?php echo $button['button'] ?> </li>	
							<!--<script type="text/javascript">
								$('<?php echo $button['id'] ?>').addClassName('non-visible');
							</script>-->			
						<?php endif;?>			
					<?php endforeach;?>  
					</ul>
			
			</div>
		</div>	
			<!--<script type="text/javascript">
				$("sociallogin-other-a").observe('click', function() {
							if(this.hasClassName('active')){
								this.removeClassName('active');
								$('sociallogin-other-button').style.display = 'none';
							}else{ 
								this.addClassName('active');
								$('sociallogin-other-button').style.display = 'block';
							}
						});
				
			</script>-->
		<?php endif; ?>
	<?php endif; ?>
</div>

<div class="clear"></div><h2>HeLLO here</h2>