<?php 
$_product=$this->getProduct();
$image=Mage::getBaseUrl('media').'catalog/product'.$_product->getSmallImage();

$link_temp=$this->helper('core/url')->getCurrentUrl();
if(strpos($link_temp,'?fb_comment_id')){
	$link=$this->helper('core/string')->substr($link_temp,0,strpos($link_temp,'?fb_comment_id'));
}else{
	$link=$link_temp;
}
 ?>
<html xmlns:fb="http://ogp.me/ns/fb#">

<link rel="image_src" href="<?php echo $image ?>"/>

<?php $isHiddenLike = $this->helper('fbcomment')->isHiddenLike()?>
<?php $isHiddenComment = $this->helper('fbcomment')->isHiddenComment()?>
<?php if(!$isHiddenComment){?>
	<div class="box-collateral fbcomment">
    	<h2><?php echo $this->__('Comments') ?></h2>
	<?php }?>

<?php if(!$isHiddenLike || !$isHiddenComment){?>    
		
<div id="fb-root"></div>
<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '<?php echo $this->getUniqueId()?>&amp', // App ID
      channelUrl : '<?php echo $link ?>', // Channel File
      status     : true, // check login status
      cookie     : true, // enable cookies to allow the server to access the session
      xfbml      : true  // parse XFBML
    });

    // Additional initialization code here
  };

  // Load the SDK Asynchronously
  (function(d){
     var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement('script'); js.id = id; js.async = true;
     js.src = "//connect.facebook.net/<?php echo $this->getLanguage() ?>/all.js";
     ref.parentNode.insertBefore(js, ref);
   }(document));
</script>



		<div class="fblike">
			<fb:comments xid="<?php echo $this->getXid()?>" href="<?php echo $link ?>"  numposts="<?php echo $this->numberOfCommment()?>" width="<?php echo $this->widthOfCommmentBox() ?>" publish_feed="<?php echo $this->publicFeed() ?>"  reverse="<?php echo $this->isReserveOrdering() ?>" simple="<?php echo !$this->isRoundedBox() ?>" css="<?php echo $this->getCssUrl() ?>">
				<fb:title></fb:title>
			</fb:comments>
		</div>
	</div>

<?php }?>

