<?php

interface Wsu_Networksecurities_Model_Interface {
    /**
     * Generates networksecurities
     *
     * @abstract
     * @return void
     */
    public function generate();

    /**
     * Checks whether word entered by user corresponds to the one generated by generate()
     *
     * @abstract
     * @param string $word
     * @return void
     */
    public function isCorrect($word);


	 /**
     * Get Block Name
     *
     * @return string
     */
    public function getBlockName();
}
